import Image from 'next/image'
import { Inter } from 'next/font/google'
import Head from 'next/head';
import { getAllPosts, getAllTags, getPostsForTopPage } from "../lib/notionAPI";
import { SinglePost } from "../components/Post/SinglePost";
import Link from 'next/link';
import Tag from '@/components/Tag/Tag';

const inter = Inter({ subsets: ['latin'] })

// SSG (Static Site Generation)
export const getStaticProps = async () => {
  // const allPosts = await getAllPosts();
  const fourPosts = await getPostsForTopPage(4);

  const allTags = await getAllTags();

  return {
    props: {
      fourPosts,
      allTags,
      // allPosts,
    },
    revalidate: 60, // ISR (Incremental Static Regeneration)
  };
};

export default function Home({/* allPosts */ fourPosts, allTags,}) {
  // console.log(allPosts);
  return (
    <div className="container w-full h-full mx-auto">
      <Head>
        <title>Notion-Blog</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="container w-full mt-16">
        <h1 className="text-5xl font-medium text-center mb-16">Notion Blog</h1>
        <div>
        {fourPosts.map((post) => (
          <div key={post.id}>
            <SinglePost
              title={post.title}
              description={post.description}
              date={post.date}
              tags={post.tags}
              slug={post.slug}
              isPaginationPage={false}
            />
          </div>
        ))}
        </div>
        <Link href="/posts/page/1" className='mb-6 lg:w-1/2 mx-auto px-5 block'>...もっと見る</Link>
        <Tag tags={allTags}/>
      </main>
    </div>
  );
}