import Image from 'next/image'
import { Inter } from 'next/font/google'
import Head from 'next/head';
import { getAllPosts, getAllTags, getPostsForTopPage } from "../lib/notionAPI";
import { SinglePost } from "../components/Post/SinglePost";
import Link from 'next/link';
import Tag from '@/components/Tag/Tag';
import Three from '@/components/Three/Three';

const inter = Inter({ subsets: ['latin'] })

type Post = {
  id: string;
  title: string;
  description: string;
  date: string;
  slug: string;
  tags: string[];
}

type Tags = string[];

type HomeProps = {
  fourPosts: Post[];
  allTags: Tags;
}

// SSG (Static Site Generation)
export const getStaticProps = async () => {
  // const allPosts = await getAllPosts();
  const fourPosts = await getPostsForTopPage(4);

  const allTags = await getAllTags();

  return {
    props: {
      fourPosts,
      allTags,
      // allPosts,
    },
    revalidate: 60, // ISR (Incremental Static Regeneration)
  };
};

export default function Home({/* allPosts */ fourPosts, allTags,}: HomeProps) {
  return (
    <div id='canvasParent' className="container w-full h-full mx-auto">
      <Head>
        <title>Notion-Blog</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="container w-full">
        <h1 className="text-5xl font-medium text-center mb-16 hidden">Notion Blog</h1>
        <Three />
        <div>
        {fourPosts.map((post) => (
          <div key={post.id}>
            <SinglePost
              title={post.title}
              description={post.description}
              date={post.date}
              tags={post.tags}
              slug={post.slug}
              isPaginationPage={false}
            />
          </div>
        ))}
        </div>
        <Link href="/posts/page/1" className='mb-16 lg:w-1/2 mx-auto px-5 block'>...もっと見る</Link>
        <Tag tags={allTags}/>
      </main>
    </div>
  );
}