import Head from "next/head";
import Link from "next/link";
import React from "react";
import Image from "next/image";
import laravelAppPic from "../public/images/pngs/laravel-app-test.png";

export default function About() {
    return (
        <div id='canvasParent' className="container w-full h-full mx-auto">
        <Head>
            <title>Notion-Blog | About Page</title>
            <meta name="description" content="Generated by create next app" />
        </Head>
        <main className="w-4/5 m-auto min-h-screen">
            <h1 className="text-5xl lg:text-8xl font-medium text-center my-16">My Projects</h1>
            <div className="relative z-0 grid w-full grid-cols-8 gap-8 sm:gap-16 mb-16">

                <div className="col-span-8 relative h-max p-8 rounded-2xl border-2 border-soliid border-black bg-white dark:border-white dark:bg-black">
                    <div className="absolute top-2 -right-4 -z-10 w-[102%] h-[102%] rounded-[1.5rem] bg-black dark:bg-white" />

                    <div className="flex flex-col lg:flex-row">
                        <div className="lg:w-1/2 lg:m-auto">
                            <Image
                                src={laravelAppPic}
                                alt="laravel_app_test"
                                className="w-full h-auto rounded-2xl p-2"
                                priority // 表示を優先
                                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
                            />
                        </div>
    
                        <div className="flex flex-col items-start justify-start p-8">
                            <span className="mb-2 text-lg">Web Application</span>
                            <h2 className="mb-2 text-3xl lg:text-4xl font-bold uppercase">EC shop Creation App</h2>
                            <p className="font-medium">
                            このアプリケーションではユーザー登録することで1アカウントにつき複数のECショップを作成し、商品を出品することができます。
                            <br />
                            このアプリはPHP, MySQL, Laravel学習の最終課題として開発しました。<br />
                            Laravel-6を使用して基本的なCRUD機能、ユーザー登録・ログイン機能や認可処理を実装しています。
                            <br />
                            また、StripeAPIを使用した簡易決済機能や登録した商品のCSVエクスポート機能も実装しています。
                            </p>
                            <div className="mt-4">
                                <Link className="bg-black dark:bg-white rounded-xl px-4 py-2 text-lg text-white dark:text-black font-medium" href="https://laravel-app-test.fly.dev/">
                                    Visit Project
                                </Link>
                            </div>
                            
                        </div>
                    </div>
                </div>
            </div>
            <h2 className="text-5xl text-center font-medium my-32">Skills</h2>
            <p className="text-center text-3xl mb-32">I&apos;ll add skills soon !!</p>
        </main>
        </div>
    );
};